id: P003121
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:41:40.892631
source_metadata:
  id: bdr:W22098
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པ་སྐུ་འཕྲེང་གསུམ་པའི་རྣམ་ཐར
  author: ''
  volumes:
    2bbc482c7cc340c587055b3429f27f64:
      image_group_id: I4223
      title: ''
      volume_number: 1
      total_pages: 407
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
