id: I2AEAC629
legacy_id: P003121
ocr_import_info:
  bdrc_scan_id: W22098
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:47:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:34:26.730842+00:00'
last_modified: 2022-09-02 04:34:39.514244
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22098
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22098
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་མཁྱེན་འཇམ་དབྱངས་བཞད་པ་སྐུ་འཕྲེང་གསུམ་པའི་རྣམ་ཐར།
  author: པྲ་ཉེ ༠༣་ངག་དབང་ཐུབ་བསྟན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9333463984605497
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4223:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4223
      total_pages: 407
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4223.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9333463984605497
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
